jump = "/Users/jonathanouwerx/code/personal/jump"
scripts = "/Users/jonathanouwerx/code/personal/scripts"
optprograms = "/Users/jonathanouwerx/opt/programs"
soff = "/Users/jonathanouwerx/code/work/soff"
